version: "3.9"
services:
  chatgpt_discord_bot:
    build: .
    restart: always
    environment:
      BOT_TOKEN: MTExMzM5NzM4MTE4NzI2MDQyNg.Gqgz2d.gkTKrLWV3YRPuLEQ7ouHxruhwT1u47nHBJt6Uw
      OPENAI_API_KEY: jigIfzFMqO2WWnJyYg5eT3BlbkFJosBDpgJzE3UWze8qOK0P
    volumes:
      - data:/data
volumes:
  data:
